Upgrade to kernel 5.15
agherzan/meta-raspberrypi pull request #1014
Opened 2022-02-18 23:17 UTC by kraj

2022-02-19 13:10 UTC, agherzan requested changes
We need a manual rebase.

2022-02-19 17:25 UTC, kraj commented
> We need a manual rebase.

done

2022-02-19 20:40 UTC, agherzan approved these changes
Cheers, @kraj!

2022-02-20 14:18 UTC, agherzan commented
@kraj this needs yet another rebase.

2022-02-21 00:16 UTC, merged