Disable Weston packageconfig options that fail to build with userland drivers
agherzan/meta-raspberrypi pull request #1118
Opened 2022-12-01 19:46 UTC by clopez

* Weston 10 (Yocto Langdale) fails to build with userland drivers when the packageconfig options `egl` or `clients` are enabled, and those are enabled by default. So disable them by default when building with `DISABLE_VC4GRAPHICS=1`

This is the build failure that happens without this patch:

```
| [105/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/launcher-direct.c
| [106/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/launcher-weston-launch.c
| [107/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/bindings.c
| [108/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/drm-formats.c
| [109/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/color-noop.c
| [110/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/log.c
| [111/470] rm -f libweston/libsession-helper.a && arm-poky-linux-gnueabi-gcc-ar csrDT libweston/libsession-helper.a libweston/libsession-helper.a.p/launcher-direct.c.o libweston/libsession-helper.a.p/launcher-util.c.o libweston/libsession-helper.a.p/launcher-weston-launch.c.o libweston/libsession-helper.a.p/dbus.c.o libweston/libsession-helper.a.p/launcher-logind.c.o
| [112/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/shared/matrix.c
| [113/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/noop-renderer.c
| [114/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/linux-sync-file.c
| [115/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c protocol/linux-dmabuf-unstable-v1-protocol.c
| [116/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/zoom.c
| [117/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/plugin-registry.c
| [118/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/weston-log-file.c
| [119/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/backend-drm/state-helpers.c
| [120/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/renderer-gl/gl-shader-config-color-transformation.c
| FAILED: libweston/renderer-gl/gl-renderer.so.p/gl-shader-config-color-transformation.c.o
| arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/renderer-gl/gl-shader-config-color-transformation.c
| ../weston-10.0.2/libweston/renderer-gl/gl-shader-config-color-transformation.c:28:10: fatal error: GLES3/gl3.h: No such file or directory
|    28 | #include <GLES3/gl3.h>
|       |          ^~~~~~~~~~~~~
| compilation terminated.
| [121/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/weston-log.c
| [122/470] rm -f libweston/backend-drm/libbacklight.a && arm-poky-linux-gnueabi-gcc-ar csrDT libweston/backend-drm/libbacklight.a libweston/backend-drm/libbacklight.a.p/libbacklight.c.o
| [123/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/content-protection.c
| [124/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/renderer-gl/gl-renderer.c
| FAILED: libweston/renderer-gl/gl-renderer.so.p/gl-renderer.c.o
| arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/renderer-gl/gl-renderer.c
| ../weston-10.0.2/libweston/renderer-gl/gl-renderer.c:32:10: fatal error: GLES3/gl3.h: No such file or directory
|    32 | #include <GLES3/gl3.h>
|       |          ^~~~~~~~~~~~~
| compilation terminated.
| [125/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/weston-log-flight-rec.c
| [126/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/weston-direct-display.c
| [127/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/libinput-device.c
| [128/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/renderer-gl/egl-glue.c
| FAILED: libweston/renderer-gl/gl-renderer.so.p/egl-glue.c.o
| arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/renderer-gl/egl-glue.c
| In file included from ../weston-10.0.2/shared/platform.h:37,
|                  from ../weston-10.0.2/libweston/renderer-gl/egl-glue.c:33:
| ../weston-10.0.2/shared/weston-egl-ext.h:153:106: error: unknown type name 'EGLAttrib'
|   153 | typedef EGLBoolean (EGLAPIENTRYP PFNEGLQUERYDEVICEATTRIBEXTPROC) (EGLDeviceEXT device, EGLint attribute, EGLAttrib *value);
|       |                                                                                                          ^~~~~~~~~
| ../weston-10.0.2/shared/weston-egl-ext.h:156:102: error: unknown type name 'EGLAttrib'
|   156 | typedef EGLBoolean (EGLAPIENTRYP PFNEGLQUERYDISPLAYATTRIBEXTPROC) (EGLDisplay dpy, EGLint attribute, EGLAttrib *value);
|       |                                                                                                      ^~~~~~~~~
| ../weston-10.0.2/shared/weston-egl-ext.h:158:95: error: unknown type name 'EGLAttrib'
|   158 | EGLAPI EGLBoolean EGLAPIENTRY eglQueryDeviceAttribEXT (EGLDeviceEXT device, EGLint attribute, EGLAttrib *value);
|       |                                                                                               ^~~~~~~~~
| ../weston-10.0.2/shared/weston-egl-ext.h:161:91: error: unknown type name 'EGLAttrib'
|   161 | EGLAPI EGLBoolean EGLAPIENTRY eglQueryDisplayAttribEXT (EGLDisplay dpy, EGLint attribute, EGLAttrib *value);
|       |                                                                                           ^~~~~~~~~
| In file included from ../weston-10.0.2/libweston/renderer-gl/egl-glue.c:36:
| ../weston-10.0.2/libweston/renderer-gl/gl-renderer-internal.h:170:9: error: unknown type name 'PFNEGLQUERYDISPLAYATTRIBEXTPROC'
|   170 |         PFNEGLQUERYDISPLAYATTRIBEXTPROC query_display_attrib;
|       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../weston-10.0.2/libweston/renderer-gl/egl-glue.c: In function 'gl_renderer_set_egl_device':
| ../weston-10.0.2/libweston/renderer-gl/egl-glue.c:461:9: error: unknown type name 'EGLAttrib'
|   461 |         EGLAttrib attrib;
|       |         ^~~~~~~~~
| ../weston-10.0.2/libweston/renderer-gl/egl-glue.c:466:14: error: called object is not a function or function pointer
|   466 |         if (!gr->query_display_attrib(gr->egl_display, EGL_DEVICE_EXT, &attrib)) {
|       |              ^~
| ../weston-10.0.2/libweston/renderer-gl/egl-glue.c: In function 'gl_renderer_setup_egl_client_extensions':
| ../weston-10.0.2/libweston/renderer-gl/egl-glue.c:580:42: warning: assignment to 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
|   580 |                 gr->query_display_attrib =
|       |                                          ^
| [129/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/linux-explicit-synchronization.c
| [130/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/backend-drm/kms.c
| [131/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/vertex-clipping.c
| [132/470] arm-poky-linux-gnueabi-gcc [...gcc-parameters-edited-for-clarity...] -c ../weston-10.0.2/libweston/touch-calibration.c
| [133/470] arm-poky [...]

2022-12-06 12:39 UTC, agherzan requested changes
A small tweak to git log as per: https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html#formatting-patches. You can see examples in git history too.

2022-12-09 04:13 UTC, clopez commented
> A small tweak to git log as per: https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html#formatting-patches. You can see examples in git history too.

just updated the git log, hope now is fine

2022-12-12 14:07 UTC, agherzan commented
@clopez any idea what caused this? Were these options enabled by default lately? Is this a new version requirement?

2022-12-12 14:07 UTC, agherzan commented
Small typo: `disablepackageconfig` -> `disable packageconfig`

2022-12-12 17:25 UTC, clopez commented
The new version of Weston (version 10 from Yocto Langdale) fails to build when using the egl headers from the RPi userland drivers.

2022-12-12 17:25 UTC, clopez commented
So it is required to disable the options that cause it to use those headers

2022-12-12 18:40 UTC, kraj approved these changes
lgtm

2022-12-13 09:39 UTC, agherzan commented
@clopez Got it now.

2022-12-13 09:39 UTC, agherzan approved these changes

2022-12-22 21:56 UTC, merged