Enable build of mesa-demos for userland graphics drivers
agherzan/meta-raspberrypi pull request #1154
Opened 2023-03-02 20:21 UTC by clopez

Enable build of mesa-demos for userland graphics drivers
* mesa-demos can be built fine if both `gles1` and `egl` options are disabled. This allows to have utilities like `glxinfo` or `glxgears`

2023-03-03 03:31 UTC, clopez commented
,mm, this is going to fail to build if the `wayland` package option gets enabled (and it gets enabled if the distro has the feature) unless poky contains this patch that [I just sent to the oe-core mailing list](https://lists.openembedded.org/g/openembedded-core/message/177973)

I guess is better that we disable wayland here as well. On this package enabling packageconfig option  `wayland` without `egl` is useless in the end.

2023-03-03 14:28 UTC, agherzan requested changes
Looks good. Thanks for this. The only request would be to keep the current git log format:

https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html

2023-03-06 14:04 UTC, clopez commented
> Looks good. Thanks for this. The only request would be to keep the current git log format:
> 
> https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html

Pushed a new commit with that format.

Thanks!

2023-03-06 15:31 UTC, agherzan approved these changes

2023-03-07 01:09 UTC, merged