Add support for Raspberry Pi Camera Module v3
agherzan/meta-raspberrypi pull request #1158
Opened 2023-03-09 10:25 UTC by Jessseee

I would like to see support for the Raspberry Pi Camera Module v3 which uses the imx708 sensor. Therefore, I added the required device tree overlay and config. I am not able to test this right now but it would be great if an admin could verify this patch.

2023-03-21 13:23 UTC, agherzan commented on recipes-bsp/bootfiles/rpi-config_git.bb
>      #fi
Looks like a mistake. @sss22213 do you know anything about this?

2023-04-03 06:50 UTC, Jessseee commented
@agherzan any updates on this?

2023-04-03 13:17 UTC, agherzan requested changes

2023-04-03 14:23 UTC, Jessseee commented on recipes-bsp/bootfiles/rpi-config_git.bb
> +    if [ "${RASPBERRYPI_CAMERA_V3}" = "1" ]; then
Done 👍
I added it to the Raspberry Pi Camera Module v2 section and I also updated a broken link.

2023-04-05 13:06 UTC, agherzan commented on docs/extra-build-config.md
> +This will add the device tree overlay imx708 ( Raspberry Pi Camera Module V3 sensor driver ) to config.txt
Looks very nice. Thanks. Can you make sure that the text wrap is consistent and that a full stop is added here?

2023-04-06 10:23 UTC, agherzan commented
Up for merge if you could also squash [docs: Fixed text wrap consistency and added full stop.](https://github.com/agherzan/meta-raspberrypi/pull/1158/commits/f7713992d4340e7474d5f303a79ca6d169a4813a) into the previous commit. There is no need for incremental changes here.

2023-04-13 09:50 UTC, Jessseee commented
The doc commits have been squashed, should I make any other changes to this PR?

2023-04-13 13:23 UTC, agherzan approved these changes
Thanks. Kicked the CI.

2023-04-13 13:26 UTC, agherzan commented
@Jessseee You have a mismatch between the commit author and the SoB line. Check the CI pipeline for DCO.

2023-04-13 13:45 UTC, Jessseee commented
@agherzan My bad, the authorship of the commits should be corrected.

2023-04-15 08:55 UTC, Jessseee commented on recipes-bsp/bootfiles/rpi-config_git.bb
>      #fi
I created a new issue addressing this #1167.

2023-04-17 10:06 UTC, merged

2023-04-27 23:31 UTC, quaresmajose commented
These break old kernels like latest 5.10 on the layer.
```
| NOTE: make -j 16 CC=aarch64-lmp-linux-gcc   -fuse-ld=bfd -fmacro-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fmacro-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/linux-raspberrypi4_64-standard-build=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/linux-raspberrypi4_64-standard-build=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot=  -fmacro-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot=  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native=  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source=/usr/src/kernel -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-build-artifacts=/usr/src/kernel  --sysroot=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot LD=aarch64-lmp-linux-ld.bfd    --sysroot=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot OBJCOPY=aarch64-lmp-linux-objcopy  HOSTCC=gcc  HOSTCFLAGS=-isystem/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/usr/include -O2 -pipe HOSTLDFLAGS=-L/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/usr/lib                         -L/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/lib                         -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/srv/oe/build/tmp-lmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 HOSTCPP=gcc  -E HOSTCXX=g++  HOSTCXXFLAGS=-isystem/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native/usr/include -O2 -pipe PAHOLE=false overlays/imx708.dtbo CC=aarch64-lmp-linux-gcc   -fuse-ld=bfd -fmacro-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fmacro-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/linux-raspberrypi4_64-standard-build=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/linux-raspberrypi4_64-standard-build=/usr/src/debug/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot=  -fmacro-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot=  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot-native=  -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source=/usr/src/kernel -fdebug-prefix-map=/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-build-artifacts=/usr/src/kernel  --sysroot=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot   LD=aarch64-lmp-linux-ld.bfd    --sysroot=/srv/oe/build/tmp-lmp/work/raspberrypi4_64-lmp-linux/linux-lmp-rpi/5.10.110+gitAUTOINC+902d575bc1_8e1110a580-r0/recipe-sysroot OBJCOPY=aarch64-lmp-linux-objcopy
| make[2]: *** No rule to make target 'arch/arm64/boot/dts/overlays/imx708.dtbo'.  Stop.
| make[1]: *** [/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source/Makefile:1358: overlays/imx708.dtbo] Error 2
| make: *** [/srv/oe/build/tmp-lmp/work-shared/raspberrypi4-64/kernel-source/Makefile:185: __sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
```

2023-05-02 08:47 UTC, quaresmajose commented
The overlays/imx708.dtbo is not supported and backport the dtbo is not accepted so one possible solutions is doping the kernel 5.10 version on the master branch https://github.com/agherzan/meta-raspberrypi/pull/1171.