Define CAN interrupt pins
agherzan/meta-raspberrypi pull request #1266
Opened 2024-01-18 10:27 UTC by dferrarigrowtech

Fixes #1264

**- What I did**
The users can now define CAN interrupt pins that are different from the hard-coded one.

**- How I did it**
I defined two more CAN variables that let users configure the CAN interrupt pins depending by the module that they used (or by their custom boards). It is similar to CAN_OSCILLATOR. I also added these variable to the documentation

Once this is merged I will cherry-pick this commit to Kirkstone (because I need this change)

2024-01-23 14:04 UTC, agherzan requested changes
Thanks! This looks good content-wise but it lacks adhering to the guidelines in https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html. Could you have a short check on it and refresh this?

2024-01-23 15:20 UTC, dferrarigrowtech commented
Thank you @agherzan! I'm not used to contributions with mail patches.
What is exactly the issue? Should I change the commit message or send the commit via email?

2024-01-23 17:23 UTC, dferrarigrowtech commented
Thank you @agherzan. I hope that now it is ok

2024-01-25 12:04 UTC, agherzan approved these changes
Thanks! Looks good.

2024-01-26 00:39 UTC, merged