rpi-base: Added missing HiFiBerry
agherzan/meta-raspberrypi pull request #1284
Opened 2024-02-19 12:06 UTC by kluszon

…Pro, DAC+ DSP, DAC+ HD, Digi Pro.

**- What I did**

Added missing support for HiFiBerry AMP100, AMP3, AMP4 Pro, DAC+ ADC Pro, DAC+ DSP, DAC+ HD, Digi Pro.

**- How I did it**

Add right lines to rpi-base.inc. Changes were tested and works fine with the branch.

2024-02-19 19:28 UTC, agherzan commented
Is this a backport from main? If not, why is this kirkstone-specific?

2024-02-20 07:08 UTC, kluszon commented
> Is this a backport from main? If not, why is this kirkstone-specific?

It's not a backport, because on **main** branch you don't have it. I'm working on **kirkstone** branch and it's a reason. It could be applied to any branch with kernel 5.10 or newer. I didn't test it with older kernels, but some **dtbo** files can be not available there.

2024-02-21 06:32 UTC, kluszon commented
@agherzan Ok then pull request prepared #1287

2024-03-05 11:17 UTC, kluszon commented
@agherzan 
Can you do a cherry-pick from 92a9b7a01245507a347c59997a3e5960b0f75ae9 to the Kirkstone branch and close it?

2024-03-18 12:12 UTC, agherzan commented
@kluszon Could you refresh this MR by recreating the branch with the cherry-pick of the commit you've prepared for master? This will kick the gears here and run the CI for kirkstone too.l

2024-03-19 06:25 UTC, kluszon commented
> @kluszon Could you refresh this MR by recreating the branch with the cherry-pick of the commit you've prepared for master? This will kick the gears here and run the CI for kirkstone too.l

Done

2024-03-27 10:36 UTC, agherzan approved these changes
Looks good.

2024-03-27 10:39 UTC, agherzan requested changes

2024-03-27 10:39 UTC, agherzan commented on conf/machine/include/rpi-base.inc
> +    overlays/hifiberry-dacplusadcpro.dtbo \
This is not an actual cherry-pick. You squashed another commit into it: https://github.com/agherzan/meta-raspberrypi/commit/fc34bc3b86f9eb42296618a3ceef82f276c472f3

Could you please include both commits for backport?

2024-04-08 17:34 UTC, agherzan commented
@kluszon the builds fail with:

| make[1]: *** No rule to make target 'arch/arm/boot/dts/overlays/hifiberry-amp4pro.dtbo'.  Stop.

2024-04-09 10:14 UTC, kluszon commented
> @kluszon the builds fail with:
> 
> | make[1]: *** No rule to make target 'arch/arm/boot/dts/overlays/hifiberry-amp4pro.dtbo'. Stop.

Your kernel doesn't have the file. I compiled it locally without any problem. What should I do with it?

2024-04-29 11:14 UTC, agherzan commented
I wish I had a kernel :)
Joke aside, you're probably building a different version, and not the default kirkstone one. You can see here https://github.com/agherzan/meta-raspberrypi/blob/master/.github/workflows/docker-images/yocto-builder/entrypoint-build.sh how the CI builds the kernel.

2024-06-03 21:56 UTC, agherzan requested changes
> The only I can do is remove the problematic amp4pro.

That should work. Could you:
1. rework the removal commit to match the contribution patch format - https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html
2. rebase on latest tip

Thanks.

2024-06-04 09:58 UTC, agherzan approved these changes
Looks good!

2024-06-04 19:49 UTC, merged