linux-raspberrypi: upgrade to 6.6.51
agherzan/meta-raspberrypi pull request #1377
Opened 2024-10-02 13:11 UTC by perezmeyer

This is a backport of https://github.com/agherzan/meta-raspberrypi/pull/1374 as requested at https://github.com/agherzan/meta-raspberrypi/pull/1375#issuecomment-2384300522

2024-10-02 13:13 UTC, perezmeyer commented
This closes https://github.com/agherzan/meta-raspberrypi/issues/1371

2024-10-09 01:05 UTC, ykuzma1 commented
@perezmeyer Sorry, I was busy with a trade show and was just able to test things. Manually applying this patch did not resolve the issue in #1371 for me. Upgrading to version 6.6.54 did not resolve it for me either.

Let me know if there is any other testing you would like me to do.

2024-10-09 12:49 UTC, perezmeyer commented
My apologies, this closes https://github.com/agherzan/meta-raspberrypi/issues/1368

2024-12-04 21:29 UTC, agherzan approved these changes

2024-12-04 21:30 UTC, agherzan commented
Looks good, thanks. Waiting for the CI.

2024-12-12 22:46 UTC, agherzan commented
Hi, @perezmeyer. Can you refresh this to cherry-pick https://github.com/agherzan/meta-raspberrypi/pull/1392?

2024-12-12 22:46 UTC, agherzan requested changes
Requires refresh from https://github.com/agherzan/meta-raspberrypi/pull/1392

2024-12-13 13:39 UTC, perezmeyer commented
At this moment I can't build and test, so I'm afraid not.

2025-01-16 17:32 UTC, agherzan commented
Superseded. Thanks.

2025-01-16 17:32 UTC, closed without merging