linux-raspberrypi_5.4.bb: Add kernel-cache source
agherzan/meta-raspberrypi pull request #731
Opened 2020-09-25 00:03 UTC by mkilivan

Fixes the following error:
ERROR. input file "cfg/virtio.scc" does not exist
fixes #730 
Signed-off-by: Murat Kilivan <murat.kilivan@gmail.com>

The `linux-raspberrypi_5.4` recipe successfully builds after this change. This patch has been tested on the dunfell branch. Probably need to apply to the other branches once it's verified.

**- What I did**

**- How I did it**

2020-09-25 01:00 UTC, kraj approved these changes

2020-09-28 09:53 UTC, mkilivan commented
Should I apply this change to the other branches under the same PR?

2020-09-28 16:38 UTC, kraj commented
I would think open individual PRs

2020-10-05 10:48 UTC, agherzan requested changes
This looks good but we would need to first push it against master and afterward backport on other branches. Could you handle that and give it a short spin?

2020-10-05 11:00 UTC, mkilivan commented
Sure, I created a new PR for the master branch. #738

2020-10-05 11:05 UTC, agherzan commented
Thanks @mkilivan . Merged.

2020-10-05 11:06 UTC, merged