Remove UART usage in U-Boot when ENABLE_UART=0
agherzan/meta-raspberrypi pull request #733
Opened 2020-09-29 13:04 UTC by tolszak

This fixes booting on Rasbpberry Pi 4 when config.txt doesn't
contain enable_uart=1. Seems like u-boot tries to write to serial
but serial doesn't exist and it stalls.

**- What I did**

**- How I did it**

2020-09-29 19:13 UTC, myfreescalewebpage commented
@tolszak for yout information I previously worked on this because uart is used for linux console too and this should be explicitly disabled to free the uart interface for another usage: https://github.com/agherzan/meta-raspberrypi/pull/588

2020-09-29 21:24 UTC, tolszak commented
My issue is related to uboot. With enable_uart=0 it doesn't boot. So it seems not really related to your issue.

2020-09-30 06:04 UTC, myfreescalewebpage commented
Not directly you're right :)

2020-10-05 16:48 UTC, agherzan requested changes
This needs more details on what actually is going on. It's also worth raising and pushing the patch to upstream. If they merge it there we can backport it here until uboot gets bumped. Also, mind the contributions conventions (git subject, description, etc) and try to keep the same tab/indentation in files. Don't forget Signed-off-by and Upstream-status.

On top of these, a change needs to first go in master (meta-raspberrypi), and once that lands, we can raise additional PRs for other branches (eg. dunfell).

2021-01-12 22:41 UTC, tolszak commented
I uploaded new fix, the old one seems not working anymore.
In short I think the issue is with u-boot kernel or device tree, it seems to expect serial port to be available while enable_uart = 0 in config.txt disables it. It causes device to hang just after loading u-boot kernel. So the patch I uploaded enforces enable_uart=1 in config.txt when RPI_USE_U_BOOT=1.

2021-01-19 09:27 UTC, agherzan commented
@tolszak do we know why this is the case? Does it sound like a bug in uboot? Have we checked with upstream? Also, if we are going for a workaround (which we will if we have details on the issue at hand) this fix needs to land first in `master`.

2021-01-19 09:41 UTC, tolszak commented
> @tolszak do we know why this is the case? Does it sound like a bug in uboot? Have we checked with upstream? Also, if we are going for a workaround (which we will if we have details on the issue at hand) this fix needs to land first in `master`.

I'm pretty sure that this bug is in u-boot. Unfortunately I don't have enough time currently to research and fix that (and I don't think it will change next weeks/months). After making a few assumptions, I just came to this workaround and left it, here, for community, in case someone else hits the same issue.

2021-01-19 09:44 UTC, agherzan commented
Understandable. Thanks for this.

2021-05-31 00:03 UTC, hommeabeil commented
I don't think it is related to u-boot well not directly and since I am not an expert in this subject it is hard for me to start debugging it. But if I use the `bootfiles` from the Zeus branch with the kernel and the the U-boot from the Dunfell branch I can get farther in the boot  sequence. In my case, I am not sure why, but the kernel seems to hang when trying to get the SD  card. Maybe the firmware does not properly configure something  .... And all of this append with `enable_uart=0`, hope this help some one. I will try to keep looking.

2021-10-30 20:31 UTC, agherzan commented
Closing due to inactivity. We can reopen if there is some interest on it.

2021-10-30 20:31 UTC, closed without merging