linux-raspberrypi: Only deploy cmdline.txt for the main kernel
agherzan/meta-raspberrypi pull request #736
Opened 2020-10-02 09:47 UTC by alexgg

When multiple kernels are being built, not all of them can deploy the same file. A use case for this is when Linux is being used as a bootloader to kexec a new kernel, and the initial one is configured differently to be much smaller in size.

This patch assumes the same command  line arguments is used by all kernels.

This is tested on the warrior branch so I PR it there. Once approved I will open a PR for master.

2020-10-02 16:38 UTC, kraj approved these changes
lgtm

2020-10-05 10:40 UTC, agherzan approved these changes

2020-10-05 10:43 UTC, agherzan commented
@alexgg thanks for this. We would need to first include this in master and afterward backport it on other branches. Could you first raise this against master?

2020-10-05 10:43 UTC, agherzan requested changes
Needs to be on master first,

2020-10-12 09:06 UTC, agherzan approved these changes
Looks good. Merged.

2020-10-12 09:06 UTC, merged