Solving issue with not finding firmware for wlan on raspberrypi zero w
agherzan/meta-raspberrypi pull request #771
Opened 2020-11-29 20:59 UTC by virusxp

**- What I did**
I was building a yocto image for my raspberry pi zero w, but the wifi device was not created on boot. The issue which caused
this error was a missing link providing the brcmfmac43430 firmware (the driver was looking for brcmfmac43430-sdio.raspberrypi,model-zero-w.txt). Creating the link in /lib/firmware/brcm solved the issue.

**- How I did it**
I added the missing link creation to the responsible recipe.

2020-11-30 01:01 UTC, kraj submitted a review, later dismissed
LGTM

2020-11-30 16:06 UTC, agherzan requested changes
The change looks good. Thanks. Can you also format the git log as per the contribution guideline? You cal also check git log for examples.

2020-11-30 20:51 UTC, virusxp commented
Oh sorry, I was to quick creating the request. I have changed the commit message to follow the contributing guideline.

2020-12-01 21:03 UTC, agherzan commented
That's absolutely fine @virusxp . Can you also rebase the branch so we get rid of that merge?

2020-12-02 20:28 UTC, virusxp commented
The rebase is done. @agherzan

2020-12-02 22:05 UTC, agherzan commented
@jenkins-ag ok to test

2020-12-03 09:37 UTC, agherzan approved these changes

2020-12-03 09:37 UTC, agherzan commented
Thanks. Merged to master.

2020-12-03 09:37 UTC, merged