Add brcmfmac43456-sdio for Pi400
agherzan/meta-raspberrypi pull request #777
Opened 2020-12-08 03:27 UTC by shawaj

Pi400 uses brcmfmac43456-sdio

**- What I did**

Pi 400 uses the Broadcom BCM43456 WiFi chip instead of the BCM43455 in the Pi 4. This adds support.

**- How I did it**

Pull in the firmware files for brcmfmac43456-sdio from the RPi-Distro repo

2020-12-08 12:04 UTC, agherzan requested changes
Looks good. If you also address the git log format (see log to contributions documentation - including SIgned off by) we can get this in.

2020-12-08 15:16 UTC, shawaj commented
@agherzan should hopefully be in the correct format now?

2020-12-08 17:40 UTC, agherzan approved these changes
Looks good now.

2020-12-08 17:40 UTC, agherzan commented
@agherzan-ci ok to test

2020-12-08 20:28 UTC, shawaj commented
@agherzan CI failed - then I realised there was an extra character lingering in the first patch.

Fixed now though

2020-12-09 00:17 UTC, agherzan approved these changes
Thanks. Merged.

2020-12-09 00:17 UTC, merged