Enable use of 'RPI_EXTRA_CONFIG += ...' in local.conf
agherzan/meta-raspberrypi pull request #792
Opened 2021-01-14 16:31 UTC by m5p3nc3r

Enable the use of RPI_EXTRA_CONFIG when targeting 64bit images on PI4.

Before this patch, use of RPI_EXTRA_CONFIG += in a local.conf would overwrite
the needed 'arm_64bit=1' defined in the core recipes.  The net result would be
a system that did not boot.

This patch fixes the assignment of 'arm_64bit=1' even if RPI_EXTRA_CONFIG
has been set elsewhere.

Signed-off-by: Your Name matthew@thespencers.me.uk

2021-01-18 15:30 UTC, agherzan requested changes
The change looks fine to me. We would need to tweak the commit log in accordance with https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html
See git history for examples.

2021-01-18 16:23 UTC, m5p3nc3r commented
Sorry, not sure what happened with the comment.  Updated, hopefully this is fine now?

2021-01-18 16:25 UTC, agherzan commented
@agherzan-ci ok to test

2021-01-19 09:24 UTC, agherzan approved these changes

2021-01-19 09:24 UTC, merged