'inherit kernel' is already required
agherzan/meta-raspberrypi pull request #799
Opened 2021-01-21 21:33 UTC by JonasVautherin

'recipes-kernel/linux/linux-yocto.inc' already inherits 'kernel'.
This commit removes the superfluous one.

Resolves #797.

2021-01-21 21:35 UTC, agherzan requested changes
Please take a short look at https://meta-raspberrypi.readthedocs.io/en/latest/contributing.html and change the commit log accordingly. Looks good otherwise.

2021-01-24 01:49 UTC, JonasVautherin commented
Seems like the CI does not run, for some reason 🤔

2021-01-24 10:02 UTC, agherzan commented
@agherzan-ci ok to test

2021-01-24 10:03 UTC, agherzan approved these changes

2021-01-26 10:07 UTC, merged