libva: Fix for when using `userland`
agherzan/meta-raspberrypi pull request #848
Opened 2021-04-15 13:29 UTC by matt-hammond-001

libva: Fix for when using `userland`

Fixes #842 - failing build of libva when using `userland` recipe.
Fix is same as: https://github.com/agherzan/meta-raspberrypi/commit/ac16b0e9d713bcc4ee0e976259064d1a318a5aac

Signed-off-by: Matt Hammond <matt.hammond@bbc.co.uk>

2021-04-23 03:26 UTC, kraj approved these changes
lgtm

2021-04-23 19:28 UTC, agherzan approved these changes

2021-04-23 19:28 UTC, agherzan commented
@agherzan-ci ok to test

2021-05-15 19:36 UTC, kraj commented
@agherzan its pending merge. Please apply it

2021-05-16 00:48 UTC, agherzan requested changes
@matt-hammond-001 @kraj Don't we need this in `master` too? If yes, can we first MR this change there and follow up with a cherry-pick MR afterwards?

2021-05-16 00:51 UTC, kraj commented
> @matt-hammond-001 @kraj Don't we need this in `master` too? If yes, can we first MR this change there and follow up with a cherry-pick MR afterwards for `dunfell`?

yes it needs to be on master too.

2021-05-16 00:54 UTC, agherzan commented
Cool. Let's do that first. @matt-hammond-001 do you think you could raise an MR against `master` first?

2021-05-16 00:58 UTC, kraj commented
> > @matt-hammond-001 @kraj Don't we need this in `master` too? If yes, can we first MR this change there and follow up with a cherry-pick MR afterwards for `dunfell`?
> 
> yes it needs to be on master too.

created pull #859 for master

2021-05-18 13:59 UTC, agherzan approved these changes
Merged the master one @kraj. I reckon we are ready to merge this one too.

2021-05-25 19:37 UTC, kraj commented
it will be good to ensure cherry-pick recognises it as backport and resolves it automatically. Otherwise it looks ok

2021-05-27 12:13 UTC, agherzan commented
@matt-hammond-001 can you cherry-pick your commit in https://github.com/agherzan/meta-raspberrypi/pull/859 and push it here?

2021-06-07 12:01 UTC, agherzan requested changes
Please cherry-pick existing commit in master.

2021-06-07 17:30 UTC, matt-hammond-001 commented
> Please cherry-pick existing commit in master.
Done ... I think?

2021-06-08 13:14 UTC, matt-hammond-001 commented
Apologies - that makes more sense. Done. Hopefully right this time.

2021-06-08 14:38 UTC, agherzan commented
@matt-hammond-001 That's absolutely alright. Looks good now.

2021-06-08 14:38 UTC, agherzan approved these changes

2021-06-08 14:39 UTC, merged