mesa: Broadcom v3d Vulkan driver
agherzan/meta-raspberrypi pull request #934
Opened 2021-11-04 16:27 UTC by jwinarske

This enables building Vulkan 1.1 compliant Broadcom driver for v3d.  Requires pending upstream poky patch (below).

Signed-off-by: Joel Winarske <joel.winarske@gmail.com>

Pending upstream patch:
```
Enables building the Vulkan 1.1 compliant v3d driver.

Signed-off-by: Joel Winarske <joel.winarske@gmail.com>
---
 meta/recipes-graphics/mesa/mesa.inc | 1 +
 1 file changed, 1 insertion(+)

diff --git a/meta/recipes-graphics/mesa/mesa.inc b/meta/recipes-graphics/mesa/mesa.inc
index cc71114992..b687f8e4ab 100644
--- a/meta/recipes-graphics/mesa/mesa.inc
+++ b/meta/recipes-graphics/mesa/mesa.inc
@@ -112,6 +112,7 @@ VULKAN_DRIVERS = ""
 VULKAN_DRIVERS:append:x86:class-target = ",intel"
 VULKAN_DRIVERS:append:x86-64:class-target = ",intel"
 VULKAN_DRIVERS:append ="${@bb.utils.contains('PACKAGECONFIG', 'freedreno', ',freedreno', '', d)}"
+VULKAN_DRIVERS:append ="${@bb.utils.contains('PACKAGECONFIG', 'broadcom', ',broadcom', '', d)}"
 PACKAGECONFIG[vulkan] = "-Dvulkan-drivers=${@strip_comma('${VULKAN_DRIVERS}')}, -Dvulkan-drivers='',"

 PACKAGECONFIG[opengl] = "-Dopengl=true, -Dopengl=false"
-- 
2.31.1

```

2021-11-04 16:35 UTC, agherzan commented
Thanks for this. Could you ping here when upstream merged the mesa support?

2021-11-04 16:51 UTC, jwinarske commented
Sure.  I will be back porting into poky honister branch as well.  Really any branch that has mesa version that has Vulkan 1.1 compliant driver.

CI job that generates images and mesa-vulkan-drivers-21.2.1-r0.cortexa72.rpm:
https://github.com/meta-flutter/meta-flutter/blob/rpi4-drm/.github/workflows/rpi4-64.yml

mesa-vulkan-drivers-21.2.1-r0.cortexa72.rpm will be available for use [here](https://github.com/meta-flutter/meta-flutter/actions/runs/1422258866) when job is complete.

Adding `opengl vulkan` to `DISTRO_FEATURES` configures mesa with:

```
        prefix:          /usr
        libdir:          lib
        includedir:      include
        
        OpenGL:          yes (ES1: yes ES2: yes)
        OSMesa:          no
        
        DRI platform:    drm
        DRI drivers:     no
        DRI driver dir:  /usr/lib/dri
        
        EGL:             yes
        EGL drivers:     builtin:egl_dri2
        EGL/Vulkan/VL platforms:   wayland surfaceless drm surfaceless drm
        GBM:             yes
        GBM backends path: /usr/lib/gbm
        
        Vulkan drivers:  broadcom
        Vulkan ICD dir:  share/vulkan/icd.d
        
        llvm:            no
        
        Gallium drivers: swrast kmsro vc4 v3d virgl
        Gallium st:      mesa
        HUD lmsensors:   no
        
        Shared-glapi:    yes
        
        Perfetto:        no
        Perfetto ds:     auto
```

```
$ rpm -qlp mesa-vulkan-drivers-21.2.1-r0.cortexa72.rpm 
/usr
/usr/lib
/usr/lib/libvulkan_broadcom.so
/usr/share
/usr/share/vulkan
/usr/share/vulkan/icd.d
/usr/share/vulkan/icd.d/broadcom_icd.aarch64.json
```

2021-11-06 03:10 UTC, jwinarske commented
I implemented a [recipe](https://github.com/jwinarske/meta-vulkan/blob/main/recipes-graphics/sascha-samples/sascha-samples_git.bb) to run Sascha Willems Vulkan samples.  The difference between this and the Khronos one is it actually installs samples...

Pre-built honister image with D2D (no X11 or Wayland): [rpi4-drm-honister-sdimage](https://github.com/meta-flutter/meta-flutter/actions/runs/1427946793 )

Most of the samples work, where the other complain about target not having adequate support.

Still waiting on upstream.

2021-11-08 18:53 UTC, jwinarske commented
http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=ddcaf3596227a32628b436f4130f4c0b1541a4be

2021-11-08 18:57 UTC, kraj approved these changes
so I suppose this will only work with master since that where needed version of mesa will be ?

2021-11-08 19:52 UTC, jwinarske commented
Anyone interested in trying out the Vulkan driver on PI4 you will want to use my new Yocto layer:
https://github.com/jwinarske/meta-vulkan

* Sascha Willems's Vulkan Sample - (individual apps) `ls /usr/bin/vulkan-samples`
* vkcube
* vkmark
* vkquake (X11 only - need to install content yourself)
* vkquake3 (need to install content yourself)
* vkrunner

2021-11-14 15:05 UTC, jwinarske commented
@agherzan This is ready to go for yocto master.

2021-11-17 21:13 UTC, jwinarske commented
@agherzan ping

2021-11-19 14:24 UTC, agherzan commented
@jwinarske did oe-core merge the mesa support? Can you reference that in git log and:
1. rebase your branch on top of master
2. use a reasonable line length for the body of the commit log (wrap 90 chars for example)

2021-11-21 21:04 UTC, jwinarske commented
@agherzan done

2021-11-24 12:02 UTC, agherzan commented
@jwinarske The branch is not rebased. You still have merge commits. As far as I can see, I would expect one commit.

2021-11-27 17:00 UTC, jwinarske commented
@agherzan A squash and merge is what I use for that.  It needs approval again.

2021-11-29 13:48 UTC, agherzan commented
@agherzan-ci ok to test

2021-11-29 13:49 UTC, agherzan commented
Thanks, @jwinarske. Looks good now. I'll start the CI engines and merge if everything goes well.

2021-12-03 11:49 UTC, agherzan requested changes
One last tweak please @jwinarske. Can you format the git log subject similar to "mesa: Enable building vulkan driver"? Thanks.

2021-12-03 16:12 UTC, jwinarske commented
@agherzan done

2021-12-03 21:32 UTC, agherzan approved these changes

2021-12-03 21:33 UTC, merged