bootfiles: allow i2c-gpio overlay
agherzan/meta-raspberrypi pull request #976
Opened 2021-12-12 09:08 UTC by mr-nice

Hi all,
this is a RFC to be able to add i2c-gpio overlays.

Defining I2C_GPIO_CONFIG = "bus=7,i2c_gpio_sda=6,i2c_gpio_scl=5"
Will configure i2c-7 bus to use gpio 6 as SDA and gpio 5 as SCL

This way of configuration has the drawback to not be able to define more then one bus. Should we define an array? I saw some other defines using _X so we could use e.g

I2C_GPIO_CONFIG_X = "i2c_gpio_sda=6,i2c_gpio_scl=5" to define bus X and check a fix list of such variables?

I'm also not sure if we should abstract the command line even further?

I2C_GPIO_CONFIG_X_SCL=6
I2C_GPIO_CONFIG_X_SDA=5

Or something like that?

2022-01-04 11:43 UTC, agherzan commented
It feels to me that we are splitting this a bit too much. I would say let's just keep the dtb installed and enable the configuration with the general extra config vairable.

2022-01-05 09:52 UTC, mr-nice commented
Hi,
thanks for the review and the imput. I changed the pull request as suggested.

2022-01-10 11:14 UTC, agherzan requested changes
Could you please squash/rebase the history - there should be only one commit. Also SoB (signed-off-by) and a bit more git log details would be useful.

2022-01-11 19:38 UTC, mr-nice commented
Thanks again for the review :) I updated the pull request as suggested.

2022-02-19 12:57 UTC, agherzan approved these changes
CI is ready so we can start it for this PR too. Thanks, @mr-nice.

2022-02-20 00:00 UTC, merged